# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Python37/Lib/site-packages/PySide2/wam/wam_bot.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(506, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 491, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.buttonMakeScreen = QtWidgets.QPushButton(self.tab_6)
        self.buttonMakeScreen.setGeometry(QtCore.QRect(9, 69, 104, 23))
        self.buttonMakeScreen.setObjectName("buttonMakeScreen")
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(119, 69, 75, 23))
        self.label_2.setObjectName("label_2")
        self.editEmul_2 = QtWidgets.QLineEdit(self.tab_6)
        self.editEmul_2.setGeometry(QtCore.QRect(200, 70, 133, 20))
        self.editEmul_2.setObjectName("editEmul_2")
        self.buttonOpenLog = QtWidgets.QPushButton(self.tab_6)
        self.buttonOpenLog.setGeometry(QtCore.QRect(8, 190, 121, 23))
        self.buttonOpenLog.setObjectName("buttonOpenLog")
        self.buttonEditAccs = QtWidgets.QPushButton(self.tab_6)
        self.buttonEditAccs.setGeometry(QtCore.QRect(10, 10, 141, 23))
        self.buttonEditAccs.setObjectName("buttonEditAccs")
        self.buttonTest = QtWidgets.QPushButton(self.tab_6)
        self.buttonTest.setGeometry(QtCore.QRect(10, 100, 101, 23))
        self.buttonTest.setObjectName("buttonTest")
        self.label_3 = QtWidgets.QLabel(self.tab_6)
        self.label_3.setGeometry(QtCore.QRect(120, 100, 361, 51))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.buttonStartRotation = QtWidgets.QPushButton(self.tab)
        self.buttonStartRotation.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.buttonStartRotation.setObjectName("buttonStartRotation")
        self.checkBoxTrain = QtWidgets.QCheckBox(self.tab)
        self.checkBoxTrain.setGeometry(QtCore.QRect(30, 50, 241, 17))
        self.checkBoxTrain.setChecked(True)
        self.checkBoxTrain.setObjectName("checkBoxTrain")
        self.buttonStopRotation = QtWidgets.QPushButton(self.tab)
        self.buttonStopRotation.setEnabled(False)
        self.buttonStopRotation.setGeometry(QtCore.QRect(110, 160, 81, 23))
        self.buttonStopRotation.setCheckable(False)
        self.buttonStopRotation.setObjectName("buttonStopRotation")
        self.editEmul = QtWidgets.QLineEdit(self.tab)
        self.editEmul.setGeometry(QtCore.QRect(100, 10, 113, 20))
        self.editEmul.setObjectName("editEmul")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 20))
        self.label.setObjectName("label")
        self.editTrainPower = QtWidgets.QLineEdit(self.tab)
        self.editTrainPower.setGeometry(QtCore.QRect(270, 48, 113, 20))
        self.editTrainPower.setObjectName("editTrainPower")
        self.editDeepDef = QtWidgets.QLineEdit(self.tab)
        self.editDeepDef.setGeometry(QtCore.QRect(315, 120, 113, 20))
        self.editDeepDef.setObjectName("editDeepDef")
        self.checkDeepDef = QtWidgets.QCheckBox(self.tab)
        self.checkDeepDef.setGeometry(QtCore.QRect(30, 90, 391, 21))
        self.checkDeepDef.setChecked(True)
        self.checkDeepDef.setObjectName("checkDeepDef")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.comboboxGrabAccFrom = QtWidgets.QComboBox(self.tab_2)
        self.comboboxGrabAccFrom.setGeometry(QtCore.QRect(100, 40, 131, 22))
        self.comboboxGrabAccFrom.setObjectName("comboboxGrabAccFrom")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 81, 20))
        self.label_16.setObjectName("label_16")
        self.editEmulGrab = QtWidgets.QLineEdit(self.tab_2)
        self.editEmulGrab.setGeometry(QtCore.QRect(100, 10, 113, 20))
        self.editEmulGrab.setObjectName("editEmulGrab")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(240, 40, 61, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.comboboxGrabAccTo = QtWidgets.QComboBox(self.tab_2)
        self.comboboxGrabAccTo.setGeometry(QtCore.QRect(310, 40, 131, 22))
        self.comboboxGrabAccTo.setObjectName("comboboxGrabAccTo")
        self.checkBoxGrabFood = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxGrabFood.setGeometry(QtCore.QRect(10, 90, 51, 17))
        self.checkBoxGrabFood.setChecked(True)
        self.checkBoxGrabFood.setObjectName("checkBoxGrabFood")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 70, 201, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.checkBoxGrabWood = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxGrabWood.setGeometry(QtCore.QRect(70, 90, 61, 17))
        self.checkBoxGrabWood.setChecked(True)
        self.checkBoxGrabWood.setObjectName("checkBoxGrabWood")
        self.checkBoxGrabBlueCrystalls = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxGrabBlueCrystalls.setGeometry(QtCore.QRect(140, 90, 111, 17))
        self.checkBoxGrabBlueCrystalls.setChecked(True)
        self.checkBoxGrabBlueCrystalls.setObjectName("checkBoxGrabBlueCrystalls")
        self.checkBoxGrabRedGems = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxGrabRedGems.setGeometry(QtCore.QRect(260, 90, 111, 17))
        self.checkBoxGrabRedGems.setChecked(True)
        self.checkBoxGrabRedGems.setObjectName("checkBoxGrabRedGems")
        self.buttonStartGrab = QtWidgets.QPushButton(self.tab_2)
        self.buttonStartGrab.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.buttonStartGrab.setObjectName("buttonStartGrab")
        self.buttonStopGrab = QtWidgets.QPushButton(self.tab_2)
        self.buttonStopGrab.setEnabled(False)
        self.buttonStopGrab.setGeometry(QtCore.QRect(90, 190, 81, 23))
        self.buttonStopGrab.setCheckable(False)
        self.buttonStopGrab.setObjectName("buttonStopGrab")
        self.buttonGrabStep1 = QtWidgets.QPushButton(self.tab_2)
        self.buttonGrabStep1.setGeometry(QtCore.QRect(220, 190, 75, 23))
        self.buttonGrabStep1.setObjectName("buttonGrabStep1")
        self.buttonGrabStep2 = QtWidgets.QPushButton(self.tab_2)
        self.buttonGrabStep2.setGeometry(QtCore.QRect(300, 190, 75, 23))
        self.buttonGrabStep2.setObjectName("buttonGrabStep2")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(70, 110, 381, 71))
        self.label_19.setTextFormat(QtCore.Qt.AutoText)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.checkBoxGrabLoginAndRotate = QtWidgets.QCheckBox(self.tab_2)
        self.checkBoxGrabLoginAndRotate.setGeometry(QtCore.QRect(218, 12, 251, 17))
        self.checkBoxGrabLoginAndRotate.setChecked(False)
        self.checkBoxGrabLoginAndRotate.setObjectName("checkBoxGrabLoginAndRotate")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.editTonusLevel = QtWidgets.QLineEdit(self.tab_7)
        self.editTonusLevel.setGeometry(QtCore.QRect(289, 72, 133, 20))
        self.editTonusLevel.setObjectName("editTonusLevel")
        self.label_6 = QtWidgets.QLabel(self.tab_7)
        self.label_6.setGeometry(QtCore.QRect(9, 66, 261, 31))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.buttonStartTonus = QtWidgets.QPushButton(self.tab_7)
        self.buttonStartTonus.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.buttonStartTonus.setObjectName("buttonStartTonus")
        self.buttonStopTonus = QtWidgets.QPushButton(self.tab_7)
        self.buttonStopTonus.setEnabled(False)
        self.buttonStopTonus.setGeometry(QtCore.QRect(100, 180, 81, 23))
        self.buttonStopTonus.setCheckable(False)
        self.buttonStopTonus.setObjectName("buttonStopTonus")
        self.editEmulTonus = QtWidgets.QLineEdit(self.tab_7)
        self.editEmulTonus.setGeometry(QtCore.QRect(90, 40, 113, 20))
        self.editEmulTonus.setObjectName("editEmulTonus")
        self.label_7 = QtWidgets.QLabel(self.tab_7)
        self.label_7.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.label_7.setObjectName("label_7")
        self.comboboxTonusAcc = QtWidgets.QComboBox(self.tab_7)
        self.comboboxTonusAcc.setGeometry(QtCore.QRect(90, 10, 131, 22))
        self.comboboxTonusAcc.setObjectName("comboboxTonusAcc")
        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 81, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.checkBoxTonusReputation = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxTonusReputation.setGeometry(QtCore.QRect(10, 120, 201, 17))
        self.checkBoxTonusReputation.setChecked(True)
        self.checkBoxTonusReputation.setObjectName("checkBoxTonusReputation")
        self.checkBoxTonusStatue = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxTonusStatue.setGeometry(QtCore.QRect(10, 140, 181, 17))
        self.checkBoxTonusStatue.setChecked(True)
        self.checkBoxTonusStatue.setObjectName("checkBoxTonusStatue")
        self.checkBoxTonusFountain = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxTonusFountain.setGeometry(QtCore.QRect(10, 160, 181, 17))
        self.checkBoxTonusFountain.setChecked(True)
        self.checkBoxTonusFountain.setObjectName("checkBoxTonusFountain")
        self.editTonusHorseStep = QtWidgets.QLineEdit(self.tab_7)
        self.editTonusHorseStep.setGeometry(QtCore.QRect(290, 96, 133, 20))
        self.editTonusHorseStep.setObjectName("editTonusHorseStep")
        self.label_9 = QtWidgets.QLabel(self.tab_7)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 271, 31))
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.checkBoxTonusAroundDragon = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxTonusAroundDragon.setGeometry(QtCore.QRect(230, 120, 241, 17))
        self.checkBoxTonusAroundDragon.setChecked(False)
        self.checkBoxTonusAroundDragon.setObjectName("checkBoxTonusAroundDragon")
        self.editTonusBuy1 = QtWidgets.QLineEdit(self.tab_7)
        self.editTonusBuy1.setGeometry(QtCore.QRect(320, 150, 31, 20))
        self.editTonusBuy1.setObjectName("editTonusBuy1")
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setGeometry(QtCore.QRect(220, 140, 91, 31))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_7)
        self.label_21.setGeometry(QtCore.QRect(360, 140, 41, 31))
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setWordWrap(True)
        self.label_21.setObjectName("label_21")
        self.checkBoxTonusLoginAndRotate = QtWidgets.QCheckBox(self.tab_7)
        self.checkBoxTonusLoginAndRotate.setGeometry(QtCore.QRect(228, 13, 251, 17))
        self.checkBoxTonusLoginAndRotate.setChecked(False)
        self.checkBoxTonusLoginAndRotate.setObjectName("checkBoxTonusLoginAndRotate")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(40, 40, 81, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(50, 70, 81, 20))
        self.label_11.setObjectName("label_11")
        self.comboboxMineAcc = QtWidgets.QComboBox(self.tab_4)
        self.comboboxMineAcc.setGeometry(QtCore.QRect(130, 40, 131, 22))
        self.comboboxMineAcc.setObjectName("comboboxMineAcc")
        self.editEmulMine = QtWidgets.QLineEdit(self.tab_4)
        self.editEmulMine.setGeometry(QtCore.QRect(130, 70, 113, 20))
        self.editEmulMine.setObjectName("editEmulMine")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(10, 94, 311, 31))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.editMineLevel = QtWidgets.QLineEdit(self.tab_4)
        self.editMineLevel.setGeometry(QtCore.QRect(330, 100, 133, 20))
        self.editMineLevel.setObjectName("editMineLevel")
        self.buttonStartMine = QtWidgets.QPushButton(self.tab_4)
        self.buttonStartMine.setGeometry(QtCore.QRect(20, 190, 75, 23))
        self.buttonStartMine.setObjectName("buttonStartMine")
        self.buttonStopMine = QtWidgets.QPushButton(self.tab_4)
        self.buttonStopMine.setEnabled(False)
        self.buttonStopMine.setGeometry(QtCore.QRect(100, 190, 81, 23))
        self.buttonStopMine.setCheckable(False)
        self.buttonStopMine.setObjectName("buttonStopMine")
        self.checkBoxMineRotation = QtWidgets.QCheckBox(self.tab_4)
        self.checkBoxMineRotation.setGeometry(QtCore.QRect(20, 160, 201, 17))
        self.checkBoxMineRotation.setChecked(True)
        self.checkBoxMineRotation.setObjectName("checkBoxMineRotation")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(10, 0, 441, 31))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.editMineTime = QtWidgets.QLineEdit(self.tab_4)
        self.editMineTime.setGeometry(QtCore.QRect(330, 126, 133, 20))
        self.editMineTime.setObjectName("editMineTime")
        self.label_14 = QtWidgets.QLabel(self.tab_4)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 311, 31))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.checkBoxMineLogin = QtWidgets.QCheckBox(self.tab_4)
        self.checkBoxMineLogin.setGeometry(QtCore.QRect(270, 40, 201, 17))
        self.checkBoxMineLogin.setChecked(True)
        self.checkBoxMineLogin.setObjectName("checkBoxMineLogin")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.editEmulFish = QtWidgets.QLineEdit(self.tab_8)
        self.editEmulFish.setGeometry(QtCore.QRect(130, 10, 133, 20))
        self.editEmulFish.setObjectName("editEmulFish")
        self.label_4 = QtWidgets.QLabel(self.tab_8)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.label_4.setObjectName("label_4")
        self.editFishCount = QtWidgets.QLineEdit(self.tab_8)
        self.editFishCount.setGeometry(QtCore.QRect(130, 40, 133, 20))
        self.editFishCount.setObjectName("editFishCount")
        self.label_5 = QtWidgets.QLabel(self.tab_8)
        self.label_5.setGeometry(QtCore.QRect(10, 38, 111, 23))
        self.label_5.setObjectName("label_5")
        self.buttonStopFish = QtWidgets.QPushButton(self.tab_8)
        self.buttonStopFish.setEnabled(False)
        self.buttonStopFish.setGeometry(QtCore.QRect(90, 80, 81, 23))
        self.buttonStopFish.setCheckable(False)
        self.buttonStopFish.setObjectName("buttonStopFish")
        self.buttonStartFish = QtWidgets.QPushButton(self.tab_8)
        self.buttonStartFish.setGeometry(QtCore.QRect(10, 80, 75, 23))
        self.buttonStartFish.setObjectName("buttonStartFish")
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WamyBoty 0.28"))
        self.buttonMakeScreen.setText(_translate("MainWindow", "Сделать скриншот"))
        self.label_2.setText(_translate("MainWindow", "Имя эмулятора"))
        self.editEmul_2.setText(_translate("MainWindow", "MEmu"))
        self.buttonOpenLog.setText(_translate("MainWindow", "Открыть лог файл"))
        self.buttonEditAccs.setText(_translate("MainWindow", "Список аккаунтов"))
        self.buttonTest.setText(_translate("MainWindow", "Тест"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Откройте в эмуляторе вид, в котором отображается снаряжение лорда. После этого нажмите кнопку Тест. Если все настройки эмулятора сделаны правильно, то через несколько секунд WamyBoty уведомит Вас, что все настроено верно.</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Тест"))
        self.buttonStartRotation.setText(_translate("MainWindow", "Запуск"))
        self.checkBoxTrain.setText(_translate("MainWindow", "Тренировать войска,если их мощь меньше "))
        self.buttonStopRotation.setText(_translate("MainWindow", "Стоп"))
        self.editEmul.setText(_translate("MainWindow", "MEmu"))
        self.label.setText(_translate("MainWindow", "Имя эмулятора"))
        self.editTrainPower.setText(_translate("MainWindow", "1500000"))
        self.editDeepDef.setText(_translate("MainWindow", "6, 7"))
        self.checkDeepDef.setText(_translate("MainWindow", "Режим глубокой защиты на твинах в заданные дни, 6,7 - выходные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ротация твинков"))
        self.label_15.setText(_translate("MainWindow", "С аккаунта"))
        self.label_16.setText(_translate("MainWindow", "Имя эмулятора"))
        self.editEmulGrab.setText(_translate("MainWindow", "MEmu3"))
        self.label_17.setText(_translate("MainWindow", "На аккаунт"))
        self.checkBoxGrabFood.setText(_translate("MainWindow", "Хлеб"))
        self.label_18.setText(_translate("MainWindow", "Забирать из рюкзака НЕбезопасные:"))
        self.checkBoxGrabWood.setText(_translate("MainWindow", "Дерево"))
        self.checkBoxGrabBlueCrystalls.setText(_translate("MainWindow", "Синие кристаллы"))
        self.checkBoxGrabRedGems.setText(_translate("MainWindow", "Красные гемы"))
        self.buttonStartGrab.setText(_translate("MainWindow", "Запуск"))
        self.buttonStopGrab.setText(_translate("MainWindow", "Стоп"))
        self.buttonGrabStep1.setText(_translate("MainWindow", "Шаг1"))
        self.buttonGrabStep2.setText(_translate("MainWindow", "Шаг2"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Шаг 1 - это все действия, связанные с твином перед разлогиниванием из него (желания Эллари, сбор известных плюшек из Центра событий, отправка героев собирать урожай)<br/>Шаг 2 - это сохранение координат твина, выход из него, заход на основу и разграбление твина под 0.</p></body></html>"))
        self.checkBoxGrabLoginAndRotate.setText(_translate("MainWindow", "Логиниться и крутить следующие аккаунты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Грабить"))
        self.editTonusLevel.setText(_translate("MainWindow", "23, 24"))
        self.label_6.setText(_translate("MainWindow", "Уровни монстров для фарма через запятую"))
        self.buttonStartTonus.setText(_translate("MainWindow", "Запуск"))
        self.buttonStopTonus.setText(_translate("MainWindow", "Стоп"))
        self.editEmulTonus.setText(_translate("MainWindow", "MEmu3"))
        self.label_7.setText(_translate("MainWindow", "Имя эмулятора"))
        self.label_8.setText(_translate("MainWindow", "Аккаунт"))
        self.checkBoxTonusReputation.setText(_translate("MainWindow", "Собирать сундуки с репутацией"))
        self.checkBoxTonusStatue.setText(_translate("MainWindow", "Посещать статуи с опытом"))
        self.checkBoxTonusFountain.setText(_translate("MainWindow", "Собирать фонтаны"))
        self.editTonusHorseStep.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Продвижений по карте до поиска"))
        self.checkBoxTonusAroundDragon.setText(_translate("MainWindow", "Перемещаться по карте вокруг дракона"))
        self.editTonusBuy1.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "Покупать тонус"))
        self.label_21.setText(_translate("MainWindow", "раз"))
        self.checkBoxTonusLoginAndRotate.setText(_translate("MainWindow", "Логиниться и крутить следующие аккаунты"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Тонус"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Сокровища"))
        self.label_10.setText(_translate("MainWindow", "Аккаунт"))
        self.label_11.setText(_translate("MainWindow", "Имя эмулятора"))
        self.editEmulMine.setText(_translate("MainWindow", "MEmu3"))
        self.label_12.setText(_translate("MainWindow", "Порядок отправки на руду"))
        self.editMineLevel.setText(_translate("MainWindow", "4, 4, 5, 6, 1"))
        self.buttonStartMine.setText(_translate("MainWindow", "Запуск"))
        self.buttonStopMine.setText(_translate("MainWindow", "Стоп"))
        self.checkBoxMineRotation.setText(_translate("MainWindow", "Включать в перерывах ротацию"))
        self.label_13.setText(_translate("MainWindow", "Для этого режима важно установить правильное число героев на аккаунте!"))
        self.editMineTime.setText(_translate("MainWindow", "30"))
        self.label_14.setText(_translate("MainWindow", "Время генерации новых рудников, указывайте 0 если не известна. Допустимые значения: 30, 40, 50"))
        self.checkBoxMineLogin.setText(_translate("MainWindow", "Перезалогиниться в начале"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Руда"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Война"))
        self.editEmulFish.setText(_translate("MainWindow", "MEmu3"))
        self.label_4.setText(_translate("MainWindow", "Имя эмулятора"))
        self.editFishCount.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "Количество забросов"))
        self.buttonStopFish.setText(_translate("MainWindow", "Стоп"))
        self.buttonStartFish.setText(_translate("MainWindow", "Запуск"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "Рыбалка"))
